- promptlayer/track/track.py
Metadata input should be a valid dictionary of key value pairs of strings
> input validation for metadata

- promptlayer/prompts/chat.py
- setup.py
> making a copy of the prompt template

- promptlayer/utils.py
- setup.py
This will be used in langchain callback
> allowing metadata in util for promptlayer_api

- promptlayer/promptlayer.py
- pyproject.toml
fixes https://github.com/MagnivOrg/prompt-layer-library/issues/60#issuecomment-1720251928
> anthropic tokens fix

- promptlayer/promptlayer.py
- pyproject.toml
> fixing anthropic bug

- promptlayer/prompts/prompts.py
- pyproject.toml
This should silence the warning added in LangChain 0.0.302 😁
> Fix import warning on PromptTemplate

- promptlayer/utils.py
- pyproject.toml
> 84-Fix streaming for anthropic

- promptlayer/__init__.py
- pyproject.toml
This pull request adds a new module called "track" to the promptlayer package, which will be used for tracking LLM requests. Additionally, the version of the package has been updated to 0.3.6.
> Add track module to promptlayer and update version

- promptlayer/prompts/prompts.py
- promptlayer/resources/base.py
- pyproject.toml
> 89-prompts.all() fails silently

- promptlayer/track/track.py
- promptlayer/utils.py
- pyproject.toml
see https://github.com/MagnivOrg/prompt-layer-api/pull/408
> Update score tracking with support for named scores.

- promptlayer/utils.py
- pyproject.toml
This pull request updates the promptlayer version to 0.4.3 and adds a new function called convert_native_object_to_dict. This function is used to convert a native object into a dictionary.
> Update promptlayer version and add convert_native_object_to_dict function

- promptlayer/prompts/chat.py
- pyproject.toml
This pull request updates the promptlayer version to 0.4.4 and removes an unnecessary condition in the chat.py file.
> Update promptlayer version to 0.4.4 and remove unnecessary condition in chat.py

- promptlayer/prompts/prompts.py
- promptlayer/templates.py
- promptlayer/types/prompt_template.py
- promptlayer/utils.py
- pyproject.toml
This pull request updates the langchain import and adds a new function called publish_prompt to the codebase. This function allows users to publish prompt templates to the PromptLayer platform.
> Update langchain import and add publish_prompt function

- promptlayer/types/prompt_template.py
- promptlayer/utils.py
- pyproject.toml
This pull request updates the typing in the prompt_template.py file and adds new fields to the PromptTemplate and PublishPromptTemplate classes.
> 109 - Update typing and add new fields to prompt_template.py

- promptlayer/templates.py
- promptlayer/types/prompt_template.py
- promptlayer/utils.py
- pyproject.toml
This pull request adds a new function `get_all_prompt_templates` that allows fetching all prompt templates from the PromptLayer API. This function will be useful for retrieving a list of all available prompt templates in the application.
> 121 - Add function for fetching all prompt templates

- promptlayer/types/prompt_template.py
- pyproject.toml
This pull request removes the typing_extensions module from the codebase.
> 124 - Remove typing_extensions module

- promptlayer/utils.py
- pyproject.toml
> working state

- promptlayer/types/prompt_template.py
- promptlayer/utils.py
- pyproject.toml
> adding ability to set release labels from library

- pyproject.toml
Addressing https://github.com/MagnivOrg/prompt-layer-library/issues/142
> Pytest moved to dev dependencies.

- promptlayer/utils.py
- pyproject.toml
This pull request updates the versions of `utils.py` and `pyproject.toml` files. The changes include fixing a bug in the `promptlayer_api_handler` function and updating the version number in the `pyproject.toml` file.
> Update utils.py and pyproject.toml versions

- .devcontainer/devcontainer.json
- promptlayer/utils.py
- pyproject.toml
This pull request fixes a bug that was causing duplicate responses in the anthropic streaming feature. The issue was resolved by updating the `ms-python.black-formatter` extension to version 2023.6.0. Additionally, a code block was modified to prevent the duplication of messages in the response.
> 160 - Fix duplicate response with anthropic streaming bug

- promptlayer/__init__.py
- promptlayer/types/prompt_template.py
- pyproject.toml
This pull request updates the version of the `promptlayer` package to 1.0.9. Additionally, it adds a new `PlaceholderMessage` type to the `Message` union.
> 166 - Update version to 1.0.9 and add placeholder message

- Makefile
- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/span_exporter.py
- pyproject.toml
> 173 - Fix hard coded workspace for /spans-bulk exporting

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
> 175 - Update traceable argument name

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/span_exporter.py
- pyproject.toml
> 178 - Do not require workspace ID for creating spans

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
> 182 - PromptLayer.run() updates

- .devcontainer/devcontainer.json
- .github/workflows/release.yml
- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
This pull request updates the dependencies and fixes a typing issue in the PromptLayer class. The dependencies have been updated to the latest versions, and the typing in the PromptLayer class has been corrected. This ensures that the code is up to date and free of typing errors.
> Update dependencies and fix typing in PromptLayer class

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
> 191 - Custom span name

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/utils.py
- pyproject.toml
> 196 - Python run workflow support

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
> 200 - Update workflow_version_number to workflow_version

- promptlayer/__init__.py
- promptlayer/utils.py
- pyproject.toml
Update the version number to 1.0.28 and modify the AzureOpenAI client initialization to use the correct parameter.
> Bump version to 1.0.28 and update AzureOpenAI client initialization

- promptlayer/__init__.py
- promptlayer/types/prompt_template.py
- pyproject.toml
Update the version to 1.0.32 and enhance the Content type to include Media and MediaVariable structures.
> Bump version to 1.0.32 and extend Content type with Media and MediaVariable

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/utils.py
- pyproject.toml
> NYC-102 - Python library workflow updates

- .devcontainer/devcontainer.json
- poetry.lock
- promptlayer/__init__.py
- promptlayer/promptlayer_mixins.py
- promptlayer/utils.py
- pyproject.toml
Update the package version and integrate Google services for chat and completion functionalities. This includes new request handling methods and adjustments to the project configuration.
> Bump version to 1.0.42 and add Google integration for chat and completion requests

- .github/workflows/release.yml
- poetry.lock
- pyproject.toml
Adjust the Python version requirement to 3.9 and modify related dependencies to ensure compatibility with the updated version.
> Update Python version requirement to 3.9 and adjust dependencies accordingly

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
> Thread the tracer through in `AsyncPromptLayer`

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/utils.py
- pyproject.toml
> LAC-257: Fixed track request for empty variable and send message

- promptlayer/__init__.py
- promptlayer/promptlayer_mixins.py
- pyproject.toml
> NYC-629 - Make async work with tracing in the python library

- promptlayer/__init__.py
- promptlayer/types/prompt_template.py
- promptlayer/utils.py
- pyproject.toml
> LAC-423: Added thinking for anthropic wrapper

- promptlayer/__init__.py
- promptlayer/types/prompt_template.py
- pyproject.toml
Change the signature type in ThinkingContent to use Union for improved clarity in type definition.
> Refactor ThinkingContent signature type for clarity

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/promptlayer_mixins.py
- pyproject.toml
Update the version to 1.0.56 and introduce optional provider and model parameters in various PromptLayer methods to enhance functionality.
> Bump version to 1.0.56 and add provider/model parameters to PromptLayer methods

- promptlayer/__init__.py
- promptlayer/utils.py
- pyproject.toml
> LAC-468: Fixed gemini to work without user message

- poetry.lock
- promptlayer/__init__.py
- promptlayer/promptlayer.py
- pyproject.toml
Introduce a new parameter, prompt_id, to the log_request function to enhance logging capabilities. Update version numbers in relevant files to reflect this change.
> Add prompt_id parameter to log_request function

- promptlayer/__init__.py
- promptlayer/promptlayer.py
- promptlayer/promptlayer_mixins.py
- pyproject.toml
Introduce model_parameter_overrides to enhance prompt template parameter preparation and internal execution. Update version to 1.0.64.
> Add model_parameter_overrides to PromptLayerMixin
